name: Alerta de cambios

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl \
            -H "Title: GitHub Actions - SPR-Practica4HolaMundo" \
            -H "Priority: default" \
            -H "Tags: github,rocket" \
            -d "Se subió nuevo código al repositorio SPR-Practica4HolaMundo en la rama main." \
            ntfy.sh/devops-itla